export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_LOGIN = 'SET_LOGIN';
export const SET_PLAYER = 'SET_PLAYER';
export const UPDATE_QUEUE = 'UPDATE_QUEUE';
